# Specify the parent image from which we build
FROM fetalsvrtk/segmentation:bounti_brain_tissue_1.00

# Set the working directory
WORKDIR /home/data/

ADD auto-seg-heart /home/auto-seg-heart
ADD auto-seg-heart /home/auto-seg-heart/
